markdown: kramdown
plugins:
  - jekyll-assets

exclude:
  - Gemfile*
  - LICENSE.md
  - README.md
  - credentials
  - lambda@edge.js
  - node_modules
  - package-lock.json
  - package.json
  - vendor

# Attempt to mirror production headers in development to catch any issues that
# may arise when deploying. Try to keep these up-to-date with lambda@edge.js
# as well as the CloudFront distribution’s Lambda@Edge function for greatest
# happiness
webrick:
  headers:
    Content-Security-Policy: "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    Referrer-Policy: "same-origin"
